//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientApplication.StockServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://tempuri.org/", ConfigurationName="StockServiceReference.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since message GetPricesForStocksRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://tempuri.org/GetPricesForStocks", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebClientApplication.StockServiceReference.GetPricesForStocksResponse GetPricesForStocks(WebClientApplication.StockServiceReference.GetPricesForStocksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://tempuri.org/GetPricesForStocks", ReplyAction="*")]
        System.Threading.Tasks.Task<WebClientApplication.StockServiceReference.GetPricesForStocksResponse> GetPricesForStocksAsync(WebClientApplication.StockServiceReference.GetPricesForStocksRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
    public partial class TheSimplestIdentity : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("Token");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://tempuri.org/")]
    public partial class StockTickerSerializable : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPricesForStocks", WrapperNamespace="https://tempuri.org/", IsWrapped=true)]
    public partial class GetPricesForStocksRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://tempuri.org/")]
        public WebClientApplication.StockServiceReference.TheSimplestIdentity TheSimplestIdentity;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://tempuri.org/", Order=0)]
        public string[] stockSymbolList;
        
        public GetPricesForStocksRequest() {
        }
        
        public GetPricesForStocksRequest(WebClientApplication.StockServiceReference.TheSimplestIdentity TheSimplestIdentity, string[] stockSymbolList) {
            this.TheSimplestIdentity = TheSimplestIdentity;
            this.stockSymbolList = stockSymbolList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPricesForStocksResponse", WrapperNamespace="https://tempuri.org/", IsWrapped=true)]
    public partial class GetPricesForStocksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://tempuri.org/", Order=0)]
        public WebClientApplication.StockServiceReference.StockTickerSerializable[] GetPricesForStocksResult;
        
        public GetPricesForStocksResponse() {
        }
        
        public GetPricesForStocksResponse(WebClientApplication.StockServiceReference.StockTickerSerializable[] GetPricesForStocksResult) {
            this.GetPricesForStocksResult = GetPricesForStocksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : WebClientApplication.StockServiceReference.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<WebClientApplication.StockServiceReference.WebServiceSoap>, WebClientApplication.StockServiceReference.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebClientApplication.StockServiceReference.GetPricesForStocksResponse WebClientApplication.StockServiceReference.WebServiceSoap.GetPricesForStocks(WebClientApplication.StockServiceReference.GetPricesForStocksRequest request) {
            return base.Channel.GetPricesForStocks(request);
        }
        
        public WebClientApplication.StockServiceReference.StockTickerSerializable[] GetPricesForStocks(WebClientApplication.StockServiceReference.TheSimplestIdentity TheSimplestIdentity, string[] stockSymbolList) {
            WebClientApplication.StockServiceReference.GetPricesForStocksRequest inValue = new WebClientApplication.StockServiceReference.GetPricesForStocksRequest();
            inValue.TheSimplestIdentity = TheSimplestIdentity;
            inValue.stockSymbolList = stockSymbolList;
            WebClientApplication.StockServiceReference.GetPricesForStocksResponse retVal = ((WebClientApplication.StockServiceReference.WebServiceSoap)(this)).GetPricesForStocks(inValue);
            return retVal.GetPricesForStocksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebClientApplication.StockServiceReference.GetPricesForStocksResponse> WebClientApplication.StockServiceReference.WebServiceSoap.GetPricesForStocksAsync(WebClientApplication.StockServiceReference.GetPricesForStocksRequest request) {
            return base.Channel.GetPricesForStocksAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebClientApplication.StockServiceReference.GetPricesForStocksResponse> GetPricesForStocksAsync(WebClientApplication.StockServiceReference.TheSimplestIdentity TheSimplestIdentity, string[] stockSymbolList) {
            WebClientApplication.StockServiceReference.GetPricesForStocksRequest inValue = new WebClientApplication.StockServiceReference.GetPricesForStocksRequest();
            inValue.TheSimplestIdentity = TheSimplestIdentity;
            inValue.stockSymbolList = stockSymbolList;
            return ((WebClientApplication.StockServiceReference.WebServiceSoap)(this)).GetPricesForStocksAsync(inValue);
        }
    }
}
